name: Validate and Deploy Prometheus helm charts to Development

on:
  push:
    branches-ignore:
      - "main"
  
  pull_request:
    branches:
      - develop    

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/helm-charts.yaml@main
    with:
      RELEASE_NAME: prometheus-kube-stack
      NAMESPACE: prometheus
      CHART_REPO_NAME: prometheus-community
      CHART_REPO_URL: https://prometheus-community.github.io/helm-charts
      CHART_NAME: kube-prometheus-stack
      CHART_VERSION: 80.6.0
      CHART_PATH: ./.chart
      VALUES_FILES: ".chart/kube-prometheus-stack/values/values_dev.yaml .chart/kube-state-metrics/values/values_dev.yaml .chart/prometheus-node-exporter/values/values_dev.yaml"
    secrets: inherit